### ISSUE TITLE
Duplicate isn't giving new field keys

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms-multi-part#84] opened 2017-01-30 20:49 UTC

**Comment by kjohnson** [comment] 2017-08-07 14:27
Seeing a new report of this issue.
Also reproduced locally.

Steps to Reproduce:
- Add new part.
- Add 3 textboxes and 1 textarea to the new part.
- Duplicate the new part.

Related #101

---

Support Ticket: https://wpninjas.kustomerapp.com/app/customers/59748de9291ce90011bd9867/event/59871e402b0b800010e17503

**Comment by kjohnson** [comment] 2017-08-09 19:26
Looks like the issue is actually double duplication. Re-closing.

**Closed by kjohnson** 2017-08-09 19:26 UTC
Labels: BUILDER: Fields
